CREATE TABLE KIND(
  ID UUID PRIMARY KEY,
  VORNAME VARCHAR(100) NOT NULL,
  GEBDATUM DATE
);

CREATE TABLE FACH (
    ID UUID PRIMARY KEY,
    BEZEICHNUNG varchar(255)
);

CREATE TABLE TESTART (
    ID UUID PRIMARY KEY,
    BEZEICHNUNG varchar(255)
);

CREATE TABLE KATEGORIE (
    ID UUID PRIMARY KEY,
    FACHID UUID,
    BEZEICHNUNG varchar(255)
);

CREATE TABLE NOTEN (
    ID UUID PRIMARY KEY,
    NAME varchar(255)
);

CREATE TABLE KLASSE (
    ID UUID PRIMARY KEY,
    FACHID UUID,
    STUFE varchar(10)
);

CREATE TABLE EINTRAG (
    ID UUID PRIMARY KEY,
    KINDID UUID,
    KLASSEID UUID,
    FACHID UUID,
    KATEGORIEID UUID,
    TESTARTID UUID,
    NOTEID UUID)
);